spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_design?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 797979
    driver-class-name: com.mysql.cj.jdbc.Driver