server:
  port: 9081

spring:
  profiles:
    active: test
  #static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB




#type-aliases-package: com.design.entity

mybatis:
  type-aliases-package: com.design.*
  #typeAliasesPackagecom: com.design.*
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl



