server:
  port: 9080

spring:
    #static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/db_novel?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB




#type-aliases-package: com.design.entity

mybatis:
  type-aliases-package: com.design.*
  #typeAliasesPackagecom: com.design.*
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl



